@origin = http://127.0.0.1:8000

### 获取某日记评论
GET {{origin}}/api/diary/12/comment


### 新建评论
POST {{origin}}/api/users/comment
content-type: application/json

{
  "user_id": 1,
  "diary_id": 12,
  "content": "asdfasdfasdfdasf"
}