@origin = http://127.0.0.1:8000

### getDiary
GET {{origin}}/api/diary

### createDiary
POST {{origin}}/api/diary
content-type: application/json

{
    "title": "diary-2",
    "content": "使用 REST ；ask的肌肤",
    "user_id": 1
}

### updateDiary
PUT {{origin}}/api/users/1/diary/1
content-type: application/json

{
    "title": "hello world",
    "content": "更新了",
    "user_id": 1
}