@origin = http://127.0.0.1:8000

### index
GET {{origin}}/api/diary

### 获取某用户的日记
GET {{origin}}/api/user/1/diary


### 获取某用户的私密日记
GET {{origin}}/api/user/1/diary?private


### create
POST {{origin}}/api/diary
content-type: application/json
Cookie: 'user_id=1'

{
    "title": "diary-2",
    "content": "222222222222222222",
    "user_id": 1
}

### update
PUT {{origin}}/api/diary/3
content-type: application/json
Cookie: 'user_id=1'

{
    "privated": true
}

### delete
DELETE {{origin}}/api/diary/4
Cookie: 'user_id=1'