@origin = http://127.0.0.1:8000

### getUserById
GET {{origin}}/api/users/1

### create
POST {{origin}}/api/users
content-type: application/json

{
  "username": "hy",
  "password": "123"
}

### login
POST {{origin}}/api/users/login
content-type: application/json

{
  "username": "hy",
  "password": "123"
}


### update
PUT {{origin}}/api/users/1
content-type: application/json

{
  "nickname": "胡耀",
  "profile": "哈哈哈哈，我拥有简介了",
  "avatar": "666"
}